name: Release
run-name: Release @ Delta AuthenticatorPro Icons - ${{ github.sha }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pip packages
        run: pip install -r requirements.txt

      - name: Install Cargo
        run: which cargo || sudo apt-get install -y cargo

      - name: Set up Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install oxipng
        run: which oxipng || cargo install oxipng

      - name: Build packs
        run: |
          for builder in build_*.py; do
            python3 $builder
          done

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: "*.iconpack"
          name: v${{ env.CURRENT_DATE }}
          tag_name: v${{ env.CURRENT_DATE }}
